name: "Conditions"

on:
  push:
    branches:
      - main
  
jobs:
  build:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting_Conditions
        if: ${{ true }}
        run: |
          echo $CONTAINS
          echo $CONTAINS1
          echo $FORMAT
          echo $TO_JSON
          echo ${{ github.triggering_actor }}
        env:
          CONTAINS: ${{ contains('GitHub Actions', 'actions') }}
          CONTAINS1: ${{ contains('GitHub Actions', 'Actions') }}
          FORMAT: ${{ format('This {0} {1}', 'is', 'cool') }}
          TO_JSON: ${{ toJSON(github.event) }}
  deploy:
    if: ${{ github.triggering_actor == 'greg-kania' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run if previous job succeeds
        run: |
          echo "Everything is working as expected"
