name: "Functions"

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting
        run: |
          echo $MYVAR
          echo $ADDITION
          echo $EVENT
        env:
          MYVAR: ${{ 'Hello' }}
          ADDITION: ${{ 1 == 2 }}
          EVENT: ${{ github.event_name }}
