name: "Expressions"

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting
        run: |
          echo $MYVAR
          echo $ADDITION
          echo $EVENT
        env:
          MYVAR ${{ 'Hello' }} world
          ADDITION: ${{ 1 == 2 }}
          EVENT: ${{ github.event_name }}
