name: "Lesson filters"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**/**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting
        run: |
          echo $MYVAR
          echo $ADDITION
          echo $EVENT
        env:
          MYVAR ${{'Hello'}} world
          ADDITION: ${{ 1 == 2 }}
          EVENT: ${{ github.event_name }}
