name: "Functions"

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Experimenting_Functions
        run: |
          echo $MYVAR
          echo $ADDITION
          echo $EVENT
        env:
          MYVAR: ${{ contains('GitHub Actions', 'actions') }}
          ADDITION: ${{ format('This {0} {1}, 'is', 'cool') }}
          EVENT: ${{ toJSON(github.event) }}
