name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run one-line script
        run: echo Hello, world!
      
      - name: run multi-line script
        run: |
          echo Add other actions to build
          echo test, and deploy your project

